var beatApp = angular.module('SongEx', []);

beatApp.controller('SongList', function($rootScope) {
	$rootScope.theSongs = [
		{"title": "Tell Me Why", "year": "1964", "album": "A Hard Day\'s Night"},
		{"title": "A Hard Day\'s Night", "year": "1964", "album": "A Hard Day\'s Night"},
		{"title": "And I Love Her", "year": "1964", "album": "A Hard Day\'s Night"},
		{"title": "Any Time at All", "year": "1964", "album": "A Hard Day\'s Night"},
		{"title": "Can\'t Buy Me Love", "year": "1964", "album": "A Hard Day\'s Night"},
		{"title": "I Should Have Known Better", "year": "1964", "album": "A Hard Day\'s Night"},
		{"title": "If I Fell", "year": "1964", "album": "A Hard Day\'s Night"},
		{"title": "I\'ll Be Back", "year": "1964", "album": "A Hard Day\'s Night"},
		{"title": "I\'ll Cry Instead", "year": "1964", "album": "A Hard Day\'s Night"},
		{"title": "I\'m Happy Just to Dance with You", "year": "1964", "album": "A Hard Day\'s Night"},
		{"title": "Things We Said Today", "year": "1964", "album": "A Hard Day\'s Night"},
		{"title": "When I Get Home", "year": "1964", "album": "A Hard Day\'s Night"},
		{"title": "You Can\'t Do That", "year": "1964", "album": "A Hard Day\'s Night"},
		{"title": "Because", "year": "1969", "album": "Abbey Road"},
		{"title": "Carry That Weight", "year": "1969", "album": "Abbey Road"},
		{"title": "Come Together", "year": "1969", "album": "Abbey Road"},
		{"title": "Golden Slumbers", "year": "1969", "album": "Abbey Road"},
		{"title": "Her Majesty", "year": "1969", "album": "Abbey Road"},
		{"title": "Here Comes the Sun", "year": "1969", "album": "Abbey Road"},
		{"title": "I Want You (She\'s So Heavy)", "year": "1969", "album": "Abbey Road"},
		{"title": "Maxwell\'s Silver Hammer", "year": "1969", "album": "Abbey Road"},
		{"title": "Mean Mr. Mustard", "year": "1969", "album": "Abbey Road"},
		{"title": "Octopus\'s Garden", "year": "1969", "album": "Abbey Road"},
		{"title": "Oh! Darling", "year": "1969", "album": "Abbey Road"},
		{"title": "Polythene Pam", "year": "1969", "album": "Abbey Road"},
		{"title": "She Came in Through the Bathroom Window", "year": "1969", "album": "Abbey Road"},
		{"title": "Something", "year": "1969", "album": "Abbey Road"},
		{"title": "Sun King", "year": "1969", "album": "Abbey Road"},
		{"title": "The End", "year": "1969", "album": "Abbey Road"},
		{"title": "You Never Give Me Your Money", "year": "1969", "album": "Abbey Road"},
		{"title": "In Spite of All the Danger", "year": "1958", "album": "Anthology 1"},
		{"title": "That\'ll Be the Day", "year": "1958", "album": "Anthology 1"},
		{"title": "Cayenne", "year": "1960", "album": "Anthology 1"},
		{"title": "Hallelujah, I Love Her So", "year": "1960", "album": "Anthology 1"},
		{"title": "You\'ll Be Mine", "year": "1960", "album": "Anthology 1"},
		{"title": "Ain\'t She Sweet", "year": "1961", "album": "Anthology 1"},
		{"title": "Cry for a Shadow", "year": "1961", "album": "Anthology 1"},
		{"title": "My Bonnie", "year": "1961", "album": "Anthology 1"},
		{"title": "Bésame Mucho", "year": "1962", "album": "Anthology 1"},
		{"title": "Hello Little Girl", "year": "1962", "album": "Anthology 1"},
		{"title": "How Do You Do It?", "year": "1962", "album": "Anthology 1"},
		{"title": "Like Dreamers Do", "year": "1962", "album": "Anthology 1"},
		{"title": "Searchin\'", "year": "1962", "album": "Anthology 1"},
		{"title": "The Sheik of Araby", "year": "1962", "album": "Anthology 1"},
		{"title": "Three Cool Cats", "year": "1962", "album": "Anthology 1"},
		{"title": "Lend Me Your Comb", "year": "1963", "album": "Anthology 1"},
		{"title": "Moonlight Bay", "year": "1963", "album": "Anthology 1"},
		{"title": "Leave My Kitten Alone", "year": "1964", "album": "Anthology 1"},
		{"title": "Shout", "year": "1964", "album": "Anthology 1"},
		{"title": "You Know What to Do", "year": "1964", "album": "Anthology 1"},
		{"title": "Free as a Bird", "year": "1995", "album": "Anthology 1"},
		{"title": "12-Bar Original", "year": "1965", "album": "Anthology 2"},
		{"title": "If You\'ve Got Trouble", "year": "1965", "album": "Anthology 2"},
		{"title": "That Means a Lot", "year": "1965", "album": "Anthology 2"},
		{"title": "Junk", "year": "1968", "album": "Anthology 3"},
		{"title": "Not Guilty", "year": "1968", "album": "Anthology 3"},
		{"title": "Step Inside Love/Los Paranoias", "year": "1968", "album": "Anthology 3"},
		{"title": "What\'s The New Mary Jane", "year": "1968", "album": "Anthology 3"},
		{"title": "All Things Must Pass", "year": "1969", "album": "Anthology 3"},
		{"title": "Come and Get It", "year": "1969", "album": "Anthology 3"},
		{"title": "Mailman, Bring Me No More Blues", "year": "1969", "album": "Anthology 3"},
		{"title": "Teddy Boy", "year": "1969", "album": "Anthology 3"},
		{"title": "Baby\'s in Black", "year": "1964", "album": "Beatles for Sale"},
		{"title": "Eight Days a Week", "year": "1964", "album": "Beatles for Sale"},
		{"title": "Every Little Thing", "year": "1964", "album": "Beatles for Sale"},
		{"title": "Everybody\'s Trying to Be My Baby", "year": "1964", "album": "Beatles for Sale"},
		{"title": "Honey Don\'t", "year": "1964", "album": "Beatles for Sale"},
		{"title": "I Don\'t Want to Spoil the Party", "year": "1964", "album": "Beatles for Sale"},
		{"title": "I\'ll Follow the Sun", "year": "1964", "album": "Beatles for Sale"},
		{"title": "I\'m a Loser", "year": "1964", "album": "Beatles for Sale"},
		{"title": "Kansas City/Hey, Hey, Hey, Hey", "year": "1964", "album": "Beatles for Sale"},
		{"title": "Mr. Moonlight", "year": "1964", "album": "Beatles for Sale"},
		{"title": "No Reply", "year": "1964", "album": "Beatles for Sale"},
		{"title": "Rock and Roll Music", "year": "1964", "album": "Beatles for Sale"},
		{"title": "What You\'re Doing", "year": "1964", "album": "Beatles for Sale"},
		{"title": "Words of Love", "year": "1964", "album": "Beatles for Sale"},
		{"title": "Taking a Trip to Carolina", "year": "1969", "album": "Fly on the Wall"},
		{"title": "Act Naturally", "year": "1965", "album": "Help!"},
		{"title": "Another Girl", "year": "1965", "album": "Help!"},
		{"title": "Dizzy, Miss Lizzy", "year": "1965", "album": "Help!"},
		{"title": "Help!", "year": "1965", "album": "Help!"},
		{"title": "I Need You", "year": "1965", "album": "Help!"},
		{"title": "It\'s Only Love", "year": "1965", "album": "Help!"},
		{"title": "I\'ve Just Seen a Face", "year": "1965", "album": "Help!"},
		{"title": "Tell Me What You See", "year": "1965", "album": "Help!"},
		{"title": "The Night Before", "year": "1965", "album": "Help!"},
		{"title": "Ticket to Ride", "year": "1965", "album": "Help!"},
		{"title": "Yesterday", "year": "1965", "album": "Help!"},
		{"title": "You Like Me Too Much", "year": "1965", "album": "Help!"},
		{"title": "You\'re Going to Lose That Girl", "year": "1965", "album": "Help!"},
		{"title": "You\'ve Got to Hide Your Love Away", "year": "1965", "album": "Help!"},
		{"title": "Across the Universe", "year": "1968", "album": "Let It Be"},
		{"title": "Dig a Pony", "year": "1969", "album": "Let It Be"},
		{"title": "Dig It", "year": "1969", "album": "Let It Be"},
		{"title": "For You Blue", "year": "1969", "album": "Let It Be"},
		{"title": "Get Back", "year": "1969", "album": "Let It Be"},
		{"title": "I\'ve Got a Feeling", "year": "1969", "album": "Let It Be"},
		{"title": "Let It Be", "year": "1969", "album": "Let It Be"},
		{"title": "Maggie Mae", "year": "1969", "album": "Let It Be"},
		{"title": "One After 909", "year": "1969", "album": "Let It Be"},
		{"title": "The Long and Winding Road", "year": "1969", "album": "Let It Be"},
		{"title": "Two of Us", "year": "1969", "album": "Let It Be"},
		{"title": "I Me Mine", "year": "1970", "album": "Let It Be"},
		{"title": "A Shot of Rhythm and Blues", "year": "1963", "album": "Live at the BBC"},
		{"title": "Carol", "year": "1963", "album": "Live at the BBC"},
		{"title": "Clarabella", "year": "1963", "album": "Live at the BBC"},
		{"title": "Crying, Waiting, Hoping", "year": "1963", "album": "Live at the BBC"},
		{"title": "Don\'t Ever Change", "year": "1963", "album": "Live at the BBC"},
		{"title": "From Us to You", "year": "1963", "album": "Live at the BBC"},
		{"title": "Glad All Over", "year": "1963", "album": "Live at the BBC"},
		{"title": "Hippy Hippy Shake", "year": "1963", "album": "Live at the BBC"},
		{"title": "I Got a Woman", "year": "1963", "album": "Live at the BBC"},
		{"title": "I Got to Find My Baby", "year": "1963", "album": "Live at the BBC"},
		{"title": "I Just Don\'t Understand", "year": "1963", "album": "Live at the BBC"},
		{"title": "I\'ll Be on My Way", "year": "1963", "album": "Live at the BBC"},
		{"title": "Keep Your Hands Off My Baby", "year": "1963", "album": "Live at the BBC"},
		{"title": "Lonesome Tears in My Eyes", "year": "1963", "album": "Live at the BBC"},
		{"title": "Lucille", "year": "1963", "album": "Live at the BBC"},
		{"title": "Memphis, Tennessee", "year": "1963", "album": "Live at the BBC"},
		{"title": "Ooh! My Soul", "year": "1963", "album": "Live at the BBC"},
		{"title": "So How Come (No One Loves Me)", "year": "1963", "album": "Live at the BBC"},
		{"title": "Soldier of Love (Lay Down Your Arms)", "year": "1963", "album": "Live at the BBC"},
		{"title": "Some Other Guy", "year": "1963", "album": "Live at the BBC"},
		{"title": "Sure to Fall (In Love with You)", "year": "1963", "album": "Live at the BBC"},
		{"title": "Sweet Little Sixteen", "year": "1963", "album": "Live at the BBC"},
		{"title": "That\'s All Right (Mama)", "year": "1963", "album": "Live at the BBC"},
		{"title": "The Honeymoon Song", "year": "1963", "album": "Live at the BBC"},
		{"title": "To Know Her is to Love Her", "year": "1963", "album": "Live at the BBC"},
		{"title": "Too Much Monkey Business", "year": "1963", "album": "Live at the BBC"},
		{"title": "Young Blood", "year": "1963", "album": "Live at the BBC"},
		{"title": "I Forgot to Remember to Forget", "year": "1964", "album": "Live at the BBC"},
		{"title": "Johnny B. Goode", "year": "1964", "album": "Live at the BBC"},
		{"title": "All You Need Is Love", "year": "1967", "album": "Magical Mystery Tour"},
		{"title": "Baby, You\'re a Rich Man", "year": "1967", "album": "Magical Mystery Tour"},
		{"title": "Blue Jay Way", "year": "1967", "album": "Magical Mystery Tour"},
		{"title": "Flying", "year": "1967", "album": "Magical Mystery Tour"},
		{"title": "Hello, Goodbye", "year": "1967", "album": "Magical Mystery Tour"},
		{"title": "I Am the Walrus", "year": "1967", "album": "Magical Mystery Tour"},
		{"title": "Magical Mystery Tour", "year": "1967", "album": "Magical Mystery Tour"},
		{"title": "Penny Lane", "year": "1967", "album": "Magical Mystery Tour"},
		{"title": "Strawberry Fields Forever", "year": "1967", "album": "Magical Mystery Tour"},
		{"title": "The Fool on the Hill", "year": "1967", "album": "Magical Mystery Tour"},
		{"title": "Your Mother Should Know", "year": "1967", "album": "Magical Mystery Tour"},
		{"title": "Beautiful Dreamer", "year": "1963", "album": "Live at the BBC "},
		{"title": "I\'m Talking About You", "year": "1963", "album": "Live at the BBC "},
		{"title": "From Me to You", "year": "1963", "album": "Past Masters "},
		{"title": "I Want to Hold Your Hand", "year": "1963", "album": "Past Masters "},
		{"title": "I\'ll Get You", "year": "1963", "album": "Past Masters "},
		{"title": "She Loves You", "year": "1963", "album": "Past Masters "},
		{"title": "Thank You Girl", "year": "1963", "album": "Past Masters "},
		{"title": "This Boy", "year": "1963", "album": "Past Masters "},
		{"title": "I Call Your Name", "year": "1964", "album": "Past Masters "},
		{"title": "I Feel Fine", "year": "1964", "album": "Past Masters "},
		{"title": "Komm Gib Mir Deine Hand", "year": "1964", "album": "Past Masters "},
		{"title": "Long Tall Sally", "year": "1964", "album": "Past Masters "},
		{"title": "Matchbox", "year": "1964", "album": "Past Masters "},
		{"title": "She\'s a Woman", "year": "1964", "album": "Past Masters "},
		{"title": "Sie Liebt Dich", "year": "1964", "album": "Past Masters "},
		{"title": "Slow Down", "year": "1964", "album": "Past Masters "},
		{"title": "Bad Boy", "year": "1965", "album": "Past Masters "},
		{"title": "I\'m Down", "year": "1965", "album": "Past Masters "},
		{"title": "Yes It Is", "year": "1965", "album": "Past Masters "},
		{"title": "Day Tripper", "year": "1965", "album": "Past Masters "},
		{"title": "We Can Work It Out", "year": "1965", "album": "Past Masters "},
		{"title": "Paperback Writer", "year": "1966", "album": "Past Masters "},
		{"title": "Rain", "year": "1966", "album": "Past Masters "},
		{"title": "Hey Jude", "year": "1968", "album": "Past Masters "},
		{"title": "Lady Madonna", "year": "1968", "album": "Past Masters "},
		{"title": "Revolution", "year": "1968", "album": "Past Masters "},
		{"title": "The Inner Light", "year": "1968", "album": "Past Masters "},
		{"title": "Don\'t Let Me Down", "year": "1969", "album": "Past Masters "},
		{"title": "Old Brown Shoe", "year": "1969", "album": "Past Masters "},
		{"title": "The Ballad of John and Yoko", "year": "1969", "album": "Past Masters "},
		{"title": "You Know My Name (Look Up the Number)", "year": "1969", "album": "Past Masters "},
		{"title": "Ask Me Why", "year": "1962", "album": "Please Please Me"},
		{"title": "Love Me Do", "year": "1962", "album": "Please Please Me"},
		{"title": "P.S. I Love You", "year": "1962", "album": "Please Please Me"},
		{"title": "Please Please Me", "year": "1962", "album": "Please Please Me"},
		{"title": "A Taste of Honey", "year": "1963", "album": "Please Please Me"},
		{"title": "Anna (Go to Him)", "year": "1963", "album": "Please Please Me"},
		{"title": "Baby It\'s You", "year": "1963", "album": "Please Please Me"},
		{"title": "Boys", "year": "1963", "album": "Please Please Me"},
		{"title": "Chains", "year": "1963", "album": "Please Please Me"},
		{"title": "Do You Want to Know a Secret", "year": "1963", "album": "Please Please Me"},
		{"title": "I Saw Her Standing There", "year": "1963", "album": "Please Please Me"},
		{"title": "Misery", "year": "1963", "album": "Please Please Me"},
		{"title": "There\'s a Place", "year": "1963", "album": "Please Please Me"},
		{"title": "Twist and Shout", "year": "1963", "album": "Please Please Me"},
		{"title": "And Your Bird Can Sing", "year": "1966", "album": "Revolver"},
		{"title": "Doctor Robert", "year": "1966", "album": "Revolver"},
		{"title": "Eleanor Rigby", "year": "1966", "album": "Revolver"},
		{"title": "For No One", "year": "1966", "album": "Revolver"},
		{"title": "Good Day Sunshine", "year": "1966", "album": "Revolver"},
		{"title": "Got to Get You into My Life", "year": "1966", "album": "Revolver"},
		{"title": "Here, There and Everywhere", "year": "1966", "album": "Revolver"},
		{"title": "I Want to Tell You", "year": "1966", "album": "Revolver"},
		{"title": "I\'m Only Sleeping", "year": "1966", "album": "Revolver"},
		{"title": "Love You To", "year": "1966", "album": "Revolver"},
		{"title": "She Said She Said", "year": "1966", "album": "Revolver"},
		{"title": "Taxman", "year": "1966", "album": "Revolver"},
		{"title": "Tomorrow Never Knows", "year": "1966", "album": "Revolver"},
		{"title": "Yellow Submarine", "year": "1966", "album": "Revolver"},
		{"title": "Drive My Car", "year": "1965", "album": "Rubber Soul"},
		{"title": "Girl", "year": "1965", "album": "Rubber Soul"},
		{"title": "If I Needed Someone", "year": "1965", "album": "Rubber Soul"},
		{"title": "I\'m Looking Through You", "year": "1965", "album": "Rubber Soul"},
		{"title": "In My Life", "year": "1965", "album": "Rubber Soul"},
		{"title": "Michelle", "year": "1965", "album": "Rubber Soul"},
		{"title": "Norwegian Wood (This Bird Has Flown)", "year": "1965", "album": "Rubber Soul"},
		{"title": "Nowhere Man", "year": "1965", "album": "Rubber Soul"},
		{"title": "Run for Your Life", "year": "1965", "album": "Rubber Soul"},
		{"title": "The Word", "year": "1965", "album": "Rubber Soul"},
		{"title": "Think for Yourself", "year": "1965", "album": "Rubber Soul"},
		{"title": "Wait", "year": "1965", "album": "Rubber Soul"},
		{"title": "What Goes On", "year": "1965", "album": "Rubber Soul"},
		{"title": "You Won\'t See Me", "year": "1965", "album": "Rubber Soul"},
		{"title": "A Day in the Life", "year": "1967", "album": "Sgt. Pepper\'s Lonely Hearts Club Band"},
		{"title": "Being for the Benefit of Mr. Kite!", "year": "1967", "album": "Sgt. Pepper\'s Lonely Hearts Club Band"},
		{"title": "Fixing a Hole", "year": "1967", "album": "Sgt. Pepper\'s Lonely Hearts Club Band"},
		{"title": "Getting Better", "year": "1967", "album": "Sgt. Pepper\'s Lonely Hearts Club Band"},
		{"title": "Good Morning, Good Morning", "year": "1967", "album": "Sgt. Pepper\'s Lonely Hearts Club Band"},
		{"title": "Lovely Rita", "year": "1967", "album": "Sgt. Pepper\'s Lonely Hearts Club Band"},
		{"title": "Lucy in the Sky with Diamonds", "year": "1967", "album": "Sgt. Pepper\'s Lonely Hearts Club Band"},
		{"title": "Sgt. Pepper\'s Lonely Hearts Club Band", "year": "1967", "album": "Sgt. Pepper\'s Lonely Hearts Club Band"},
		{"title": "Sgt. Pepper\'s Lonely Hearts Club Band (Reprise)", "year": "1967", "album": "Sgt. Pepper\'s Lonely Hearts Club Band"},
		{"title": "She\'s Leaving Home", "year": "1967", "album": "Sgt. Pepper\'s Lonely Hearts Club Band"},
		{"title": "When I\'m Sixty-Four", "year": "1967", "album": "Sgt. Pepper\'s Lonely Hearts Club Band"},
		{"title": "With a Little Help from My Friends", "year": "1967", "album": "Sgt. Pepper\'s Lonely Hearts Club Band"},
		{"title": "Within You Without You", "year": "1967", "album": "Sgt. Pepper\'s Lonely Hearts Club Band"},
		{"title": "Back in the U.S.S.R.", "year": "1968", "album": "The Beatles"},
		{"title": "Birthday", "year": "1968", "album": "The Beatles"},
		{"title": "Blackbird", "year": "1968", "album": "The Beatles"},
		{"title": "Cry Baby Cry", "year": "1968", "album": "The Beatles"},
		{"title": "Dear Prudence", "year": "1968", "album": "The Beatles"},
		{"title": "Don\'t Pass Me By", "year": "1968", "album": "The Beatles"},
		{"title": "Everybody\'s Got Something to Hide Except Me and My Monkey", "year": "1968", "album": "The Beatles"},
		{"title": "Glass Onion", "year": "1968", "album": "The Beatles"},
		{"title": "Good Night", "year": "1968", "album": "The Beatles"},
		{"title": "Happiness Is a Warm Gun", "year": "1968", "album": "The Beatles"},
		{"title": "Helter Skelter", "year": "1968", "album": "The Beatles"},
		{"title": "Honey Pie", "year": "1968", "album": "The Beatles"},
		{"title": "I Will", "year": "1968", "album": "The Beatles"},
		{"title": "I\'m So Tired", "year": "1968", "album": "The Beatles"},
		{"title": "Julia", "year": "1968", "album": "The Beatles"},
		{"title": "Long, Long, Long", "year": "1968", "album": "The Beatles"},
		{"title": "Martha My Dear", "year": "1968", "album": "The Beatles"},
		{"title": "Mother Nature\'s Son", "year": "1968", "album": "The Beatles"},
		{"title": "Ob-La-Di, Ob-La-Da", "year": "1968", "album": "The Beatles"},
		{"title": "Piggies", "year": "1968", "album": "The Beatles"},
		{"title": "Revolution 1", "year": "1968", "album": "The Beatles"},
		{"title": "Revolution 9", "year": "1968", "album": "The Beatles"},
		{"title": "Rocky Raccoon", "year": "1968", "album": "The Beatles"},
		{"title": "Savoy Truffle", "year": "1968", "album": "The Beatles"},
		{"title": "Sexy Sadie", "year": "1968", "album": "The Beatles"},
		{"title": "The Continuing Story of Bungalow Bill", "year": "1968", "album": "The Beatles"},
		{"title": "While My Guitar Gently Weeps", "year": "1968", "album": "The Beatles"},
		{"title": "Why Don\'t We Do It in the Road?", "year": "1968", "album": "The Beatles"},
		{"title": "Wild Honey Pie", "year": "1968", "album": "The Beatles"},
		{"title": "Yer Blues", "year": "1968", "album": "The Beatles"},
		{"title": "All I\'ve Got to Do", "year": "1963", "album": "With the Beatles"},
		{"title": "All My Loving", "year": "1963", "album": "With the Beatles"},
		{"title": "Devil in Her Heart", "year": "1963", "album": "With the Beatles"},
		{"title": "Don\'t Bother Me", "year": "1963", "album": "With the Beatles"},
		{"title": "Hold Me Tight", "year": "1963", "album": "With the Beatles"},
		{"title": "I Wanna Be Your Man", "year": "1963", "album": "With the Beatles"},
		{"title": "It Won\'t Be Long", "year": "1963", "album": "With the Beatles"},
		{"title": "Little Child", "year": "1963", "album": "With the Beatles"},
		{"title": "Money (That\'s What I Want)", "year": "1963", "album": "With the Beatles"},
		{"title": "Not a Second Time", "year": "1963", "album": "With the Beatles"},
		{"title": "Please Mr. Postman", "year": "1963", "album": "With the Beatles"},
		{"title": "Roll Over Beethoven", "year": "1963", "album": "With the Beatles"},
		{"title": "Till There Was You", "year": "1963", "album": "With the Beatles"},
		{"title": "You\'ve Really Got a Hold on Me", "year": "1963", "album": "With the Beatles"},
		{"title": "All Together Now", "year": "1967", "album": "Yellow Submarine"},
		{"title": "It\'s All Too Much", "year": "1967", "album": "Yellow Submarine"},
		{"title": "Only a Northern Song", "year": "1967", "album": "Yellow Submarine"},
		{"title": "Hey Bulldog", "year": "1968", "album": "Yellow Submarine"}
	];
});